// flow-typed signature: 39d5746585484ab17eb566d2bea156a2
// flow-typed version: <<STUB>>/cli-progress_v3.9.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-progress/cli-progress' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/eta' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/format-bar' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/format-time' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/format-value' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/formatter' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/generic-bar' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/multi-bar' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/options' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/single-bar' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/terminal' {
  declare module.exports: any;
}

declare module 'cli-progress/presets' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/legacy' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/rect' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/shades-classic' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/shades-grey' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-progress/cli-progress.js' {
  declare module.exports: $Exports<'cli-progress/cli-progress'>;
}
declare module 'cli-progress/lib/eta.js' {
  declare module.exports: $Exports<'cli-progress/lib/eta'>;
}
declare module 'cli-progress/lib/format-bar.js' {
  declare module.exports: $Exports<'cli-progress/lib/format-bar'>;
}
declare module 'cli-progress/lib/format-time.js' {
  declare module.exports: $Exports<'cli-progress/lib/format-time'>;
}
declare module 'cli-progress/lib/format-value.js' {
  declare module.exports: $Exports<'cli-progress/lib/format-value'>;
}
declare module 'cli-progress/lib/formatter.js' {
  declare module.exports: $Exports<'cli-progress/lib/formatter'>;
}
declare module 'cli-progress/lib/generic-bar.js' {
  declare module.exports: $Exports<'cli-progress/lib/generic-bar'>;
}
declare module 'cli-progress/lib/multi-bar.js' {
  declare module.exports: $Exports<'cli-progress/lib/multi-bar'>;
}
declare module 'cli-progress/lib/options.js' {
  declare module.exports: $Exports<'cli-progress/lib/options'>;
}
declare module 'cli-progress/lib/single-bar.js' {
  declare module.exports: $Exports<'cli-progress/lib/single-bar'>;
}
declare module 'cli-progress/lib/terminal.js' {
  declare module.exports: $Exports<'cli-progress/lib/terminal'>;
}
declare module 'cli-progress/presets/index' {
  declare module.exports: $Exports<'cli-progress/presets'>;
}
declare module 'cli-progress/presets/index.js' {
  declare module.exports: $Exports<'cli-progress/presets'>;
}
declare module 'cli-progress/presets/legacy.js' {
  declare module.exports: $Exports<'cli-progress/presets/legacy'>;
}
declare module 'cli-progress/presets/rect.js' {
  declare module.exports: $Exports<'cli-progress/presets/rect'>;
}
declare module 'cli-progress/presets/shades-classic.js' {
  declare module.exports: $Exports<'cli-progress/presets/shades-classic'>;
}
declare module 'cli-progress/presets/shades-grey.js' {
  declare module.exports: $Exports<'cli-progress/presets/shades-grey'>;
}
