name: PR AutoLabeler

on:
  pull_request_target:

jobs:
  label:
    name: Auto Labeler
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: pr autolabeler
        uses: actions/labeler@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
