name: ci-cd
on:
  push:
    branches:
      - '**/*'
  pull_request:
  release:
    types: [released]
jobs:
  unit:
    name: unit tests, node ${{ matrix.node }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [18, 19]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install NPM Packages
        run: yarn install --immutable
      - name: Check licenses
        run: yarn build:license-checker
      - name: Test
        run: yarn test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: var-${{ matrix.node }}
          path: var
        if: always()
