name: Validate Dependabot Config

on:
  pull_request:
    paths:
      - ".github/dependabot.yml"
      - ".github/workflows/dependabot-validate.yml"
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Dependabot
        id: validate
        uses: marocchino/validate-dependabot@v1
      - name: Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          header: validate-dependabot
          message: ${{ steps.validate.outputs.markdown }}
