name: Sync Labels

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml

jobs:
  sync:
    name: Sync Labels
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync Labels
        uses: b4b4r07/github-labeler@master
        id: labeler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
