name: Package Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  yarn:
    name: Yarn Lock Changes
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Yarn Lock Changes
        uses: CumulusDS/yarn-lock-changes-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  deprecation:
    name: Package Deprecations
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Check for deprecated packages
        uses: CumulusDS/deprecated-packages-action@v1
